apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: ifrm-alert-manager-api
spec:
  selector:
    matchLabels:
      app: ifrm-alert-manager-api
  replicas: 3

  template:
    metadata:
      labels:
          app: ifrm-alert-manager-api
    spec:
      containers:
        - name: ifrm-alert-manager-api
          image: "atulkhot/alertmgr-c"
          ports:
            - name: management
              containerPort: 8558
          readinessProbe:
            httpGet:
              path: "/ready"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx256m -Dconfig.resource=production.conf"
            - name: APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: ifrm-alert-manager-secret
                  key: secret
            - name: ORACLE_URL
              value: "jdbc:oracle:thin:@oracleserver:1521/ORCLPDB1"
            - name: ORACLE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: oracle-ifrm-case-review
                  key: username
            - name: ORACLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oracle-ifrm-case-review
                  key: password
            - name: IFRM_REDIS_HOST
              value: "redisserver"
            - name: IFRM_REDIS_SENTINEL_ON
              value: "false"
            - name: IFRM_AUTH_TOKEN_REDIS_TTL
              value: "40000"
            - name: CASSANDRA_SERVICE_NAME
              value: "_cql._tcp.extcassandra.myproject.svc.cluster.local"
            - name: CASSANDRA_USERNAME
              value: ""
            - name: CASSANDRA_PASSWORD
              value: ""
            - name: ZEEBE_BROKER_URL
              value: "zeebeserver.default.svc.cluster.local:26500"
            - name: WORKFLOW_RPSL_CASE_BPMNPROCESSID
              value: "rpsl-case-management"
            - name: WORKFLOW_RECEIVE_TASK_ASSIGN_TXN
              value: "assign-txn"
            - name: WORKFLOW_RECEIVE_TASK_AUTO_HOLD
              value: "auto-hold"
            - name: IFRM_TRANSACTIONMONITORING_REQUEST_TOPIC
              value: "transactionmonitoring-request-topic-name"
            - name: IFRM_TXN_HOLD_TOPIC
              value: "RPSL_CONTROL_CENTER"
            - name: IFRM_HOLD_RELEASE_ADDHOLDTRANSACTION
              value: "/fnr/rpsl/holdrelease/merchant/addholdtransaction"
            - name: IFRM_HOLD_RELEASE_ADDRELEASETRANSACTION
              value: "/fnr/rpsl/holdrelease/merchant/addreleasetransaction"
            - name: IFRM_HOLD_RELEASE_ADDBULKRELEASETRANSACTION
              value: "/fnr/rpsl/holdrelease/merchant/addbulkreleasetransaction"
            - name: KAFKA_SERVICE_NAME
              value: "_tcp-clients._tcp.my-cluster-kafka-brokers.myproject.svc.cluster.local"
            - name: REQUIRED_CONTACT_POINT_NR
              value: "3"

---
apiVersion: v1
kind: Service
metadata:
  name: ifrm-alert-manager-api
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9000
  selector:
    app: ifrm-alert-manager-api
  type: LoadBalancer
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-alert-manager
  namespace: myproject
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-alert-manager
  namespace: myproject
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: pod-alert-manager
  apiGroup: rbac.authorization.k8s.io
