apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: ifrm-prefilter-api
spec:
  selector:
    matchLabels:
      app: ifrm-prefilter-api
  replicas: 3

  template:
    metadata:
      labels:
          app: ifrm-prefilter-api
    spec:
      containers:
        - name: ifrm-prefilter-api
          image: "atulkhot/prefilter-d"
          ports:
            - name: management
              containerPort: 8558
          readinessProbe:
            httpGet:
              path: "/ready"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx256m -Dconfig.resource=production.conf"
            - name: APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: ifrm-prefilter-application-secret
                  key: secret
            - name: ORACLE_URL
              value: "jdbc:oracle:thin:@oracleserver:1521/ORCLPDB1"
            - name: ORACLE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: oracle-ifrm-prefilter
                  key: username
            - name: ORACLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oracle-ifrm-prefilter
                  key: password
            - name: IFRM_REDIS_HOST
              value: "redisserver"
            - name: IFRM_REDIS_SENTINEL_ON
              value: "false"
            - name: IFRM_AUTH_TOKEN_REDIS_TTL
              value: "40000"
            - name: IFRM_PREFILTER_CALCULATE_TPS_INTERVAL_SECONDS
              value: "10"
            - name: IFRM_RPSL_PREFILTER_SKIPPED_TXN_TOPIC
              value: "skipped-txn-topic-name"
            - name: IFRM_KAFKA_KERBEROS_ON
              value: "false"
            - name: KAFKA_URL
              value: "kafkaserver.myproject.svc.cluster.local:9092"
            - name: KAFKA_SERVICE_NAME
              value: "my-cluster-kafka-brokers.myproject.svc.cluster.local:9092"
            - name: REQUIRED_CONTACT_POINT_NR
              value: "3"

---
apiVersion: v1
kind: Service
metadata:
  name: ifrm-prefilter-api
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9000
  selector:
    app: ifrm-prefilter-api
  type: LoadBalancer
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-prefilter
  namespace: myproject
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-prefilter
  namespace: myproject
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: pod-prefilter
  apiGroup: rbac.authorization.k8s.io
